### ISSUE TITLE
BMI example dependencies not included in environment file

### ISSUE THREAD

**Issue by shelbyahrendt** [csdms/ivy#24]
current environment installation does not include the dependencies to run the bmi-run-model.ipynb.

**Comment by mdpiper** [comment]
@shelbyahrendt Thank you for this!

**Comment by mdpiper** [comment]
Currently, I can add the `bmipy` package, but the bmi-example-python repo still needs to be packaged for distribution; see https://github.com/csdms/bmi/issues/72.

**Comment by mdpiper** [comment]
I'm going to defer this for now because of debate on https://github.com/csdms/bmi/issues/72.

For ESPIn 2021, I'll ask participants to clone the bmi-example-python repository, then build/install the *bmi-heat* package from source. This should be straightforward on the CSDMS JupyterHub or on a local system because we'll be using a conda env with all dependencies installed. This is clearly a workaround, but it could be useful, too--a demonstration of cloning a repo and installing the software it contains.
