### ISSUE TITLE
Homework for ESPIn 2021 day 2

### ISSUE THREAD

**Issue by mdpiper** [csdms/ivy#46]
The "Writing stand-alone Python scripts" section of the Python Basics lesson was a little harder than intended today because we hadn't sufficiently covered the prerequisites for it; i.e., `git`, GitHub, and `conda`. These should now be satisfied. For homework today, please try the following:

1. Clone the ESPIn repo to your local machine
1. Read over the [conda lesson](https://github.com/csdms/espin/blob/main/lessons/conda/index.md)
1. Create the *espin* environment from the environment file in the repo
1. Activate the environment; can you import *numpy*?
1. Run the script from the "Writing stand-alone Python scripts" section

Feel free to add questions/comments to this issue!

**Comment by taranguiz** [comment]
When I want to run the script is showing me the following error with numpy: 


(espin) Tamaras-Mac-mini:python taranguiz$ python script_3_homework.py 
Traceback (most recent call last):
  File "/opt/anaconda3/envs/espin/lib/python3.9/site-packages/numpy/core/__init__.py", line 22, in <module>
    from . import multiarray
  File "/opt/anaconda3/envs/espin/lib/python3.9/site-packages/numpy/core/multiarray.py", line 12, in <module>
    from . import overrides
  File "/opt/anaconda3/envs/espin/lib/python3.9/site-packages/numpy/core/overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
ImportError: dlopen(/opt/anaconda3/envs/espin/lib/python3.9/site-packages/numpy/core/_multiarray_umath.cpython-39-darwin.so, 2): Library not loaded: @rpath/libopenblas.dylib
  Referenced from: /opt/anaconda3/envs/espin/lib/python3.9/site-packages/numpy/core/_multiarray_umath.cpython-39-darwin.so
  Reason: image not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/taranguiz/Desktop/espin/lessons/python/script_3_homework.py", line 1, in <module>
    import numpy as np
  File "/opt/anaconda3/envs/espin/lib/python3.9/site-packages/numpy/__init__.py", line 145, in <module>
    from . import core
  File "/opt/anaconda3/envs/espin/lib/python3.9/site-packages/numpy/core/__init__.py", line 48, in <module>
    raise ImportError(msg)
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.9 from "/opt/anaconda3/envs/espin/bin/python"
  * The NumPy version is: "1.20.2"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: dlopen(/opt/anaconda3/envs/espin/lib/python3.9/site-packages/numpy/core/_multiarray_umath.cpython-39-darwin.so, 2): Library not loaded: @rpath/libopenblas.dylib
  Referenced from: /opt/anaconda3/envs/espin/lib/python3.9/site-packages/numpy/core/_multiarray_umath.cpython-39-darwin.so
  Reason: image not found

**Comment by eb-mars** [comment]
Windows users who have Anaconda installed, here are the full list of tips to getting on with this homework, using conda, These were all posted on the ESPIn slack, but I thought it would be a handy place to cover all I came across as a windows user:

- To use conda on a Windows machine, open Anaconda or Windows "PowerShell" 
- Before creating and activating the environment (step 3 of the h/w), i.e. before calling "$ conda env create --file=environment.yaml", you'll need to comment out the "pymt_sedflux" component in the "environment.yaml" file (i just used notepad on my windows machine to add a "#", since there is no nano and i am not familiar with any other text editors)
- then, to activate the environment, instead of using "$ source activate espin" you'll type "$ conda activate espin" - _as of now I'm not sure how or why this is different._
- then before running the 'topoprofiler' script, you'll probably need to modify the directory to the data, i used "./topo.asc" in the script file, and called the topoprofiler script using: "$ python ./topoprofiler.py" in the command window.

I hope that helps anyone using windows! :) As a windows user, I would be keen to hear about any general other issues and their solutions?

**Comment by mdpiper** [comment]
Marking this issue as resolved.

The *numpy* problem is transient, but it's good we talked about it and documented it here.

I marked *pymt_sedflux* as unix-only in the `environment.yaml` file. I also updated the conda lesson to use `conda activate [env]` and note that `source` may need to be substituted if you haven't done the recommended conda setup on Linux and macOS.
